package com.nguyeha;

import java.time.LocalDate;

public class Task {

    private int id;
    private String title;
    private LocalDate dueDate;
    private String priority;
    private String description;
    private boolean status;  // true if completed, false otherwise

    // Constructor without id, typically used when creating a new task (id is auto-generated by the database)
    public Task(String title, LocalDate dueDate, String priority, String description) {
        this.title = title;
        this.dueDate = dueDate;
        this.priority = priority;
        this.description = description;
        this.status = false;  // default status is not completed
    }

    // Constructor with all attributes, used when retrieving a task from the database
    public Task(int id, String title, LocalDate dueDate, String priority, String description, boolean status) {
        this.id = id;
        this.title = title;
        this.dueDate = dueDate;
        this.priority = priority;
        this.description = description;
        this.status = status;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", dueDate=" + dueDate +
                ", priority='" + priority + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                '}';
    }
}
